### ISSUE TITLE
does it used with python2 ？

### ISSUE THREAD

**Issue by a13202026257** [YDHCUI/CNVD-2020-10487-Tomcat-Ajp-lfi#5]
,firstly , I got mistakes in makefile() , then I change bufsize args to buffering , then line get errors,：print("".join([d.data for d in data]))
Error: sequence item 0: expected str instance, bytes found
can you give me  some suggestions?
thks

**Comment by saucer-man** [comment]
yes, it only supports python2, to use python3 , you make the following changes:
1. self.socket.makefile("rb", bufsize=0) -->change self.socket.makefile("rb", buffering=0)
2. print("".join([d.data for d in data])) -->print("".join([d.data.decode() for d in data]))

**Comment by cyb3rm0nk1947** [comment]
After implementing the aforementioned changes, I am still getting the error. 

Traceback (most recent call last):
  File "AJPGhostcat.py", line 295, in <module>
    t = Tomcat(args.target, args.port)
  File "AJPGhostcat.py", line 262, in __init__
    self.stream = self.socket.makefile("rb", buffering=0)
TypeError: makefile() got an unexpected keyword argument 'buffering' 

Kindly suggest what more can be done.
